"""Base classes for agents."""
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional
from datetime import datetime
from enum import Enum


class SeverityLevel(Enum):
    """Alert severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ErrorType(Enum):
    """Types of payment errors."""
    DUPLICATE_BOOKING = "duplicate_booking"
    SPLIT_BOOKING_ERROR = "split_booking_error"
    DRA_MISMATCH = "dra_mismatch"
    ZERO_MARGIN = "zero_margin"
    EOD_BOUNDARY_CROSSING = "eod_boundary_crossing"
    MARGIN_SWING = "margin_swing"
    TIMEOUT = "timeout"
    UNKNOWN = "unknown"


@dataclass
class FindingsObject:
    """
    Standard findings object returned by all agents.

    This is the contract between agents and the orchestrator.
    Each agent must return findings in this format.
    """
    agent_name: str
    timestamp: datetime
    client_id: Optional[str]
    value_date: Optional[str]
    error_type: ErrorType
    severity: SeverityLevel
    confidence_score: float  # 0.0 to 1.0

    # Evidence
    description: str
    evidence: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Recommendations
    recommendation: Optional[str] = None
    similar_incidents: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "agent_name": self.agent_name,
            "timestamp": self.timestamp.isoformat(),
            "client_id": self.client_id,
            "value_date": self.value_date,
            "error_type": self.error_type.value,
            "severity": self.severity.value,
            "confidence_score": self.confidence_score,
            "description": self.description,
            "evidence": self.evidence,
            "metadata": self.metadata,
            "recommendation": self.recommendation,
            "similar_incidents": self.similar_incidents
        }


@dataclass
class Alert:
    """
    Complete alert object with all agent findings.

    Generated by the orchestrator after aggregating all agent findings.
    """
    alert_id: str
    timestamp: datetime
    client_id: str
    value_date: str

    # Scoring
    ensemble_score: float  # 0.0 to 1.0 (legacy)
    confidence_level: SeverityLevel

    # Risk Assessment
    risk_score: float = 0.0  # 0-100: Comprehensive risk score
    risk_level: str = "minimal"  # critical, high, medium, low, minimal
    risk_factors: List[str] = field(default_factory=list)
    mitigating_factors: List[str] = field(default_factory=list)

    # Findings from agents
    agent_findings: List[FindingsObject] = field(default_factory=list)

    # Resolution
    resolution_recommendation: Optional[str] = None
    similar_past_incidents: List[Dict[str, Any]] = field(default_factory=list)

    # Audit
    audit_log: List[Dict[str, Any]] = field(default_factory=list)

    # Status
    status: str = "pending"  # pending, investigating, resolved, dismissed
    assigned_to: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "alert_id": self.alert_id,
            "timestamp": self.timestamp.isoformat(),
            "client_id": self.client_id,
            "value_date": self.value_date,
            "ensemble_score": self.ensemble_score,
            "confidence_level": self.confidence_level.value,
            "risk_score": self.risk_score,
            "risk_level": self.risk_level,
            "risk_factors": self.risk_factors,
            "agent_findings": [f.to_dict() for f in self.agent_findings],
            "resolution_recommendation": self.resolution_recommendation,
            "similar_past_incidents": self.similar_past_incidents,
            "audit_log": self.audit_log,
            "status": self.status,
            "assigned_to": self.assigned_to
        }
